version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sev-shim
    goos:
      - linux
    goarch:
      - amd64

nfpms:
  - package_name: tinfoil-sev-shim
    file_name_template: "{{ .ProjectName }}_{{ .Version }}"
    vendor: Tinfoil
    maintainer: Tinfoil <contact@tinfoil.sh>
    section: utils
    priority: extra
    formats:
      - deb
    contents:
      - src: ./systemd/tinfoil-sev-shim.service
        dst: /lib/systemd/system/tinfoil-sev-shim.service
        type: config
    scripts:
      postinstall: systemd/postinstall.sh
      preremove: systemd/preremove.sh
      postremove: systemd/postremove.sh

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
